// <auto-generated />
namespace WeTalk.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class FixedEntities2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FixedEntities2));
        
        string IMigrationMetadata.Id
        {
            get { return "202204202237598_FixedEntities2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
